-- HovaLett schema + RLS
create extension if not exists "pgcrypto";

create table if not exists public.bejelentesek (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  report_code text,
  tipus text not null check (tipus in ('talalt','keresett')),
  kategoria text not null,
  cim text,
  leiras text,
  lat double precision not null,
  lng double precision not null,
  created_at timestamptz not null default now(),
  image_url text,
  status text not null default 'aktiv'
);

alter table public.bejelentesek
  add column if not exists report_code text;

create unique index if not exists bejelentesek_report_code_key
  on public.bejelentesek (report_code)
  where report_code is not null;

create table if not exists public.uzenetek (
  id bigint generated by default as identity primary key,
  from_user_id uuid not null references auth.users(id) on delete cascade,
  to_user_id uuid not null references auth.users(id) on delete cascade,
  report_id bigint not null references public.bejelentesek(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.bejelentesek enable row level security;
alter table public.uzenetek enable row level security;

-- csak bejelentkezett user hozhat létre adatot
drop policy if exists "bejelentesek_insert_auth" on public.bejelentesek;
create policy "bejelentesek_insert_auth"
  on public.bejelentesek for insert
  to authenticated
  with check (auth.uid() = user_id);

-- saját bejelentéseket láthatja
drop policy if exists "bejelentesek_select_own" on public.bejelentesek;
create policy "bejelentesek_select_own"
  on public.bejelentesek for select
  to authenticated
  using (auth.uid() = user_id);

-- saját bejelentést módosíthatja
drop policy if exists "bejelentesek_update_own" on public.bejelentesek;
create policy "bejelentesek_update_own"
  on public.bejelentesek for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- saját bejelentést törölheti
drop policy if exists "bejelentesek_delete_own" on public.bejelentesek;
create policy "bejelentesek_delete_own"
  on public.bejelentesek for delete
  to authenticated
  using (auth.uid() = user_id);

-- opcionális: publikus térképhez olvasható bejelentések
drop policy if exists "bejelentesek_select_public" on public.bejelentesek;
create policy "bejelentesek_select_public"
  on public.bejelentesek for select
  to anon
  using (true);

-- üzeneteket csak a küldő és címzett láthatja
drop policy if exists "uzenetek_select_participants" on public.uzenetek;
create policy "uzenetek_select_participants"
  on public.uzenetek for select
  to authenticated
  using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "uzenetek_insert_sender" on public.uzenetek;
create policy "uzenetek_insert_sender"
  on public.uzenetek for insert
  to authenticated
  with check (auth.uid() = from_user_id);

insert into storage.buckets (id, name, public)
values ('report-images', 'report-images', true)
on conflict (id) do nothing;

drop policy if exists "storage_public_read_report_images" on storage.objects;
create policy "storage_public_read_report_images"
  on storage.objects for select
  using (bucket_id = 'report-images');

drop policy if exists "storage_auth_upload_report_images" on storage.objects;
create policy "storage_auth_upload_report_images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'report-images');
