-- HovaLett schema + RLS
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.bejelentesek (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  report_code text,
  tipus text not null check (tipus in ('talalt','keresett')),
  kategoria text not null,
  cim text,
  leiras text,
  lat double precision not null,
  lng double precision not null,
  created_at timestamptz not null default now(),
  image_url text,
  status text not null default 'aktiv'
);

alter table public.bejelentesek
  drop constraint if exists bejelentesek_status_check;

alter table public.bejelentesek
  add constraint bejelentesek_status_check
  check (status in ('aktiv', 'review', 'lezart', 'rejected'));

alter table public.bejelentesek
  add column if not exists report_code text;

create unique index if not exists bejelentesek_report_code_key
  on public.bejelentesek (report_code)
  where report_code is not null;

create or replace function public.generate_report_code()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := lpad(floor(random() * 1000000)::text, 6, '0');
    exit when not exists (
      select 1
      from public.bejelentesek b
      where b.report_code = candidate
    );
  end loop;

  return candidate;
end;
$$;

create or replace function public.set_report_code_before_insert()
returns trigger
language plpgsql
as $$
begin
  if new.report_code is null or btrim(new.report_code) = '' then
    new.report_code := public.generate_report_code();
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_report_code_before_insert on public.bejelentesek;
create trigger trg_set_report_code_before_insert
before insert on public.bejelentesek
for each row
execute function public.set_report_code_before_insert();

update public.bejelentesek
set report_code = public.generate_report_code()
where report_code is null or btrim(report_code) = '';

create table if not exists public.uzenetek (
  id bigint generated by default as identity primary key,
  from_user_id uuid not null references auth.users(id) on delete cascade,
  to_user_id uuid not null references auth.users(id) on delete cascade,
  report_id bigint not null references public.bejelentesek(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.abuse_reports (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.bejelentesek(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 100),
  note text,
  status text not null default 'open' check (status in ('open', 'reviewed', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz
);

create index if not exists abuse_reports_report_created_idx
  on public.abuse_reports (report_id, created_at desc);

create index if not exists abuse_reports_reporter_created_idx
  on public.abuse_reports (reporter_user_id, created_at desc);

create unique index if not exists abuse_reports_unique_open_by_user
  on public.abuse_reports (report_id, reporter_user_id)
  where status = 'open';

create index if not exists bejelentesek_created_at_idx
  on public.bejelentesek (created_at desc);

create index if not exists bejelentesek_status_created_at_idx
  on public.bejelentesek (status, created_at desc);

create index if not exists bejelentesek_user_created_at_idx
  on public.bejelentesek (user_id, created_at desc);

create index if not exists uzenetek_from_user_created_at_idx
  on public.uzenetek (from_user_id, created_at desc);

create index if not exists uzenetek_to_user_created_at_idx
  on public.uzenetek (to_user_id, created_at desc);

create index if not exists uzenetek_report_created_at_idx
  on public.uzenetek (report_id, created_at desc);

create index if not exists profiles_role_idx
  on public.profiles (role);

alter table public.bejelentesek enable row level security;
alter table public.uzenetek enable row level security;
alter table public.profiles enable row level security;
alter table public.abuse_reports enable row level security;

create or replace function public.enforce_simple_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  hourly_count integer;
  daily_count integer;
begin
  if auth.uid() is null then
    raise exception 'Bejelentkezés szükséges.';
  end if;

  if TG_TABLE_NAME = 'bejelentesek' then
    select count(*)
      into hourly_count
      from public.bejelentesek b
      where b.user_id = auth.uid()
        and b.created_at > now() - interval '1 hour';
    if hourly_count >= 5 then
      raise exception 'Túl sok bejelentés az elmúlt 1 órában (max: 5).';
    end if;

    select count(*)
      into daily_count
      from public.bejelentesek b
      where b.user_id = auth.uid()
        and b.created_at > now() - interval '24 hours';
    if daily_count >= 20 then
      raise exception 'Túl sok bejelentés az elmúlt 24 órában (max: 20).';
    end if;
  elsif TG_TABLE_NAME = 'uzenetek' then
    select count(*)
      into hourly_count
      from public.uzenetek u
      where u.from_user_id = auth.uid()
        and u.created_at > now() - interval '1 hour';
    if hourly_count >= 60 then
      raise exception 'Túl sok üzenet az elmúlt 1 órában (max: 60).';
    end if;
  elsif TG_TABLE_NAME = 'abuse_reports' then
    select count(*)
      into hourly_count
      from public.abuse_reports a
      where a.reporter_user_id = auth.uid()
        and a.created_at > now() - interval '1 hour';
    if hourly_count >= 20 then
      raise exception 'Túl sok jelentés az elmúlt 1 órában (max: 20).';
    end if;
  end if;

  return NEW;
end;
$$;

drop trigger if exists trg_rate_limit_bejelentesek on public.bejelentesek;
create trigger trg_rate_limit_bejelentesek
before insert on public.bejelentesek
for each row
execute function public.enforce_simple_rate_limit();

drop trigger if exists trg_rate_limit_uzenetek on public.uzenetek;
create trigger trg_rate_limit_uzenetek
before insert on public.uzenetek
for each row
execute function public.enforce_simple_rate_limit();

drop trigger if exists trg_rate_limit_abuse_reports on public.abuse_reports;
create trigger trg_rate_limit_abuse_reports
before insert on public.abuse_reports
for each row
execute function public.enforce_simple_rate_limit();

-- profil automatikus létrehozás új auth userhez
create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row
execute function public.handle_new_user_profile();

insert into public.profiles (id)
select id
from auth.users
on conflict (id) do nothing;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_select_admin" on public.profiles;
create policy "profiles_select_admin"
  on public.profiles for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "profiles_update_admin" on public.profiles;
create policy "profiles_update_admin"
  on public.profiles for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- csak bejelentkezett user hozhat létre adatot
drop policy if exists "bejelentesek_insert_auth" on public.bejelentesek;
create policy "bejelentesek_insert_auth"
  on public.bejelentesek for insert
  to authenticated
  with check (auth.uid() = user_id);

-- publikus térképen csak az aktív bejelentések láthatók (anon + authenticated)
drop policy if exists "bejelentesek_select_public" on public.bejelentesek;
drop policy if exists "bejelentesek_select_active" on public.bejelentesek;
create policy "bejelentesek_select_active"
  on public.bejelentesek for select
  to public
  using (status = 'aktiv');

-- bejelentkezett felhasználó a saját bejelentéseit mindig láthatja
drop policy if exists "bejelentesek_select_own" on public.bejelentesek;
create policy "bejelentesek_select_own"
  on public.bejelentesek for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "bejelentesek_select_admin" on public.bejelentesek;
create policy "bejelentesek_select_admin"
  on public.bejelentesek for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- saját bejelentést módosíthatja
drop policy if exists "bejelentesek_update_own" on public.bejelentesek;
create policy "bejelentesek_update_own"
  on public.bejelentesek for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "bejelentesek_update_admin" on public.bejelentesek;
create policy "bejelentesek_update_admin"
  on public.bejelentesek for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- saját bejelentést törölheti
drop policy if exists "bejelentesek_delete_own" on public.bejelentesek;
create policy "bejelentesek_delete_own"
  on public.bejelentesek for delete
  to authenticated
  using (auth.uid() = user_id);

-- üzeneteket csak a küldő és címzett láthatja
drop policy if exists "uzenetek_select_participants" on public.uzenetek;
create policy "uzenetek_select_participants"
  on public.uzenetek for select
  to authenticated
  using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "uzenetek_insert_sender" on public.uzenetek;
create policy "uzenetek_insert_sender"
  on public.uzenetek for insert
  to authenticated
  with check (auth.uid() = from_user_id);

-- csak a küldő szerkesztheti az üzenetét
drop policy if exists "uzenetek_update_sender" on public.uzenetek;
create policy "uzenetek_update_sender"
  on public.uzenetek for update
  to authenticated
  using (auth.uid() = from_user_id)
  with check (auth.uid() = from_user_id);

-- küldő vagy címzett törölheti az üzenetet
drop policy if exists "uzenetek_delete_participants" on public.uzenetek;
create policy "uzenetek_delete_participants"
  on public.uzenetek for delete
  to authenticated
  using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "abuse_reports_insert_auth" on public.abuse_reports;
create policy "abuse_reports_insert_auth"
  on public.abuse_reports for insert
  to authenticated
  with check (auth.uid() = reporter_user_id);

drop policy if exists "abuse_reports_select_own" on public.abuse_reports;
create policy "abuse_reports_select_own"
  on public.abuse_reports for select
  to authenticated
  using (auth.uid() = reporter_user_id);

drop policy if exists "abuse_reports_select_admin" on public.abuse_reports;
create policy "abuse_reports_select_admin"
  on public.abuse_reports for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "abuse_reports_update_admin" on public.abuse_reports;
create policy "abuse_reports_update_admin"
  on public.abuse_reports for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

insert into storage.buckets (id, name, public)
values ('report-images', 'report-images', true)
on conflict (id) do nothing;

drop policy if exists "storage_public_read_report_images" on storage.objects;
create policy "storage_public_read_report_images"
  on storage.objects for select
  using (bucket_id = 'report-images');

drop policy if exists "storage_auth_upload_report_images" on storage.objects;
create policy "storage_auth_upload_report_images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'report-images');
